In [8]:
'''
Set path to the folder of used python files
'''
import sys
import pandas as pd
# sys.path.insert(0, '/Users/lynnjiang/liuGit/Pybook/Clinic-Analysis/Scripts/Data_Cleaning')
# from Abstract import Abstract

In [3]:
aa = Abstract()

In [4]:
# procedures_df = aa.read_data('PROCEDUREEVENTS_MV')
# procedures_df[:20]

In [12]:
procedures_icd_df = aa.read_data('PROCEDURES_ICD').dropna(subset=['ICD9_CODE'])

In [20]:
## SEQ_NUM: provides the order in which the procedures were performed.
procedures_icd_df['VALUE']=1
procedures_icd_df.sort_values(by='SUBJECT_ID')
procedures_vec = pd.pivot_table(procedures_icd_df, index=['SUBJECT_ID'], columns=['ICD9_CODE'],\
                               values=['VALUE']).fillna(0)
procedures_vec.head()

           VALUE                                              ...             \
ICD9_CODE   10   11   12   13   14   15   16   17   18   21   ...  9977 9978
SUBJECT_ID                                                    ...
2            0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0
3            0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0
4            0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0
5            0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0
6            0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0


ICD9_CODE  9979 9981 9982 9983 9984 9988 9995 9999
SUBJECT_ID
2           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6           0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 2009 columns]

In [23]:
procedures_vec = procedures_vec.reset_index()
# procedures_vec.columns
procedures_vec.columns = procedures_vec.columns.droplevel(0)

In [24]:
procedures_vec.head()

ICD9_CODE,,10,11,12,13,14,15,16,17,18,...,9977,9978,9979,9981,9982,9983,9984,9988,9995,9999
0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
aa.write2file(procedures_vec,'USER_VECTORS/procedures_uservectors')

In [8]:
d_icd_procedures_df = aa.read_data('D_ICD_PROCEDURES')
d_icd_procedures_df[:20]

,ROW_ID,ICD9_CODE,SHORT_TITLE,LONG_TITLE
0,264,851,Canthotomy,Canthotomy
1,265,852,Blepharorrhaphy,Blepharorrhaphy
2,266,859,Adjust lid position NEC,Other adjustment of lid position
3,267,861,Lid reconst w skin graft,Reconstruction of eyelid with skin flap or graft
4,268,862,Lid reconst w muc graft,Reconstruction of eyelid with mucous membrane ...
5,269,863,Lid reconst w hair graft,Reconstruction of eyelid with hair follicle graft
6,270,864,Lid recon-tarsoconj flap,Reconstruction of eyelid with tarsoconjunctiva...
7,271,869,Lid reconstr w graft NEC,Other reconstruction of eyelid with flaps or g...
8,272,870,Lid reconstruction NOS,"Reconstruction of eyelid, not otherwise specified"
9,273,871,Lid marg recon-part thic,"Reconstruction of eyelid involving lid margin,..."
10,274,872,Lid recons-part thic NEC,"Other reconstruction of eyelid, partial-thickness"
11,275,873,Lid marg recons ful thic,"Reconstruction of eyelid involving lid margin,..."
12,276,874,Lid reconst-ful thic NEC,"Other reconstruction of eyelid, full-thickness"
13,277,881,Linear rep lid lacer,Linear repair of laceration of eyelid or eyebrow
14,278,882,Lid marg lac rx-part th,"Repair of laceration involving lid margin, par..."
15,279,883,Lid lacer rx-prt th NEC,"Other repair of laceration of eyelid, partial-..."
16,280,884,Lid marg lac rx-ful thic,"Repair of laceration involving lid margin, ful..."
17,281,885,Lid lac rx-ful thic NEC,"Other repair of laceration of eyelid, full-thi..."
18,282,886,Lower lid rhytidectomy,Lower eyelid rhytidectomy
19,283,887,Upper lid rhytidectomy,Upper eyelid rhytidectomy